import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import { readFileSync, existsSync } from "fs";
import path from "path";

// ─── Dhub navigation.json types ──────────────────────────────────────────────

interface NavNode {
  type: "tab" | "folder" | "group" | "page" | "link" | "divider";
  label?: string;
  path?: string;
  url?: string;
  children?: NavNode[];
}

// ─── Convert navigation.json → Docusaurus sidebar ────────────────────────────

function convertNodes(nodes: NavNode[]): any[] {
  return nodes
    .map((node) => {
      switch (node.type) {
        case "folder":
          return {
            type: "category",
            label: node.label,
            collapsed: true,
            items: convertNodes(node.children || []),
          };
        case "group":
          return {
            type: "category",
            label: node.label,
            collapsed: false,
            items: convertNodes(node.children || []),
          };
        case "page": {
          // "docs/tutorial/foo.md" → "tutorial/foo"
          const id = (node.path || "")
            .replace(/^docs\//, "")
            .replace(/\.mdx?$/, "");
          // Don't set explicit label — let Docusaurus read the doc's own
          // title/sidebar_label from the translated .md frontmatter.
          // Category labels are handled by current.json translations.
          return { type: "doc", id };
        }
        case "link":
          return { type: "link", label: node.label, href: node.url };
        case "divider":
          return { type: "html", value: '<hr class="sidebar-divider" />' };
        default:
          return null;
      }
    })
    .filter(Boolean);
}

function loadFromNavigationJson(): SidebarsConfig | null {
  const navPath = path.resolve(__dirname, "navigation.json");
  if (!existsSync(navPath)) return null;

  try {
    const nav: NavNode[] = JSON.parse(readFileSync(navPath, "utf-8"));
    const tab = nav.find((n) => n.type === "tab" && n.path === "docs");
    if (!tab || !tab.children) return null;

    return { docsSidebar: convertNodes(tab.children) };
  } catch {
    console.warn("Failed to parse navigation.json, falling back to autogenerated sidebar.");
    return null;
  }
}

// ─── Fallback: Docusaurus autogenerated sidebar ──────────────────────────────

function autogeneratedFallback(): SidebarsConfig {
  return { docsSidebar: [{ type: "autogenerated", dirName: "." }] };
}

// ─── Export ──────────────────────────────────────────────────────────────────

const dhNavigation = loadFromNavigationJson();
const sidebars: SidebarsConfig = dhNavigation || autogeneratedFallback();

export default sidebars;
