import React, { useState, useEffect, useRef } from 'react';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import './styles.css';
import MarkdownRenderer from './MarkdownRenderer';

interface ContextDoc {
  title: string;
  url: string;
  content: string;
}

interface AiSearchModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const I18N_STRINGS: Record<string, Record<string, string>> = {
  "zh-Hans": {
    modalTitle: "REBOCAP AI 搜索",
    badge: "DeepSeek 驱动",
    placeholder: "输入你的问题",
    submitBtn: "提问",
    thinkingBtn: "思考中...",
    loadingText: "DeepSeek 正在分析知识库并生成解答...",
    errorPrefix: "请求出错：",
    sourcesTitle: "📑 参考文档：",
    aiNotice: "结果由 AI 基于 REBOCAP 官方文档生成，仅供参考",
    copy: "复制",
    copied: "已复制",
    liked: "已点赞",
  },
  "zh-Hant": {
    modalTitle: "REBOCAP AI 搜尋",
    badge: "DeepSeek 驅動",
    placeholder: "輸入你的問題",
    submitBtn: "提問",
    thinkingBtn: "思考中...",
    loadingText: "DeepSeek 正在分析知識庫並生成解答...",
    errorPrefix: "請求出錯：",
    sourcesTitle: "📑 參考文檔：",
    aiNotice: "結果由 AI 基於 REBOCAP 官方文檔生成，僅供參考",
    copy: "複製",
    copied: "已複製",
    liked: "已點贊",
  },
  en: {
    modalTitle: "REBOCAP AI Search",
    badge: "Powered by DeepSeek",
    placeholder: "Type your question here",
    submitBtn: "Ask",
    thinkingBtn: "Thinking...",
    loadingText: "DeepSeek is analyzing docs and generating an answer...",
    errorPrefix: "Error: ",
    sourcesTitle: "📑 Reference Docs:",
    aiNotice: "Results generated by AI based on REBOCAP official documentation.",
    copy: "Copy",
    copied: "Copied",
    liked: "Liked",
  },
  ja: {
    modalTitle: "REBOCAP AI 検索",
    badge: "DeepSeek 駆動",
    placeholder: "質問を入力してください",
    submitBtn: "検索",
    thinkingBtn: "思考中...",
    loadingText: "DeepSeek がドキュメントを分析して回答を生成中...",
    errorPrefix: "エラー：",
    sourcesTitle: "📑 参照ドキュメント：",
    aiNotice: "結果は REBOCAP 公式ドキュメントに基づいて AI が生成した参考情報です",
    copy: "コピー",
    copied: "コピー完了",
    liked: "高評価",
  },
};

export default function AiSearchModal({ isOpen, onClose }: AiSearchModalProps): React.ReactNode {
  const { i18n } = useDocusaurusContext();
  const locale = i18n?.currentLocale || 'zh-Hans';
  const t = I18N_STRINGS[locale] || I18N_STRINGS['zh-Hans'];

  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [answer, setAnswer] = useState('');
  const [error, setError] = useState('');
  const [sources, setSources] = useState<ContextDoc[]>([]);
  const [liked, setLiked] = useState(false);
  const [disliked, setDisliked] = useState(false);
  const [copied, setCopied] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const handleCopy = () => {
    if (!answer) return;
    navigator.clipboard.writeText(answer);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 150);
    }
  }, [isOpen]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const handleSearch = async (targetQuery?: string) => {
    const q = (targetQuery || query).trim();
    if (!q || loading) return;

    if (targetQuery) {
      setQuery(targetQuery);
    }

    setLoading(true);
    setError('');
    setAnswer('');
    setSources([]);

    let contextDocs: ContextDoc[] = [];

    // Attempt client-side Pagefind search context retrieval if available
    try {
      if (typeof window !== 'undefined' && (window as any).pagefind) {
        const pagefind = (window as any).pagefind;
        const searchRes = await pagefind.search(q);
        if (searchRes && Array.isArray(searchRes.results)) {
          const topResults = searchRes.results.slice(0, 4);
          for (const res of topResults) {
            const data = await res.data();
            if (data) {
              const docTitle = data.meta?.title || '文档页面';
              if (Array.isArray(data.sub_results) && data.sub_results.length > 0) {
                for (const sub of data.sub_results.slice(0, 2)) {
                  contextDocs.push({
                    title: `${docTitle} > ${sub.title || '具体章节'}`,
                    url: sub.url || data.url || '#',
                    content: (sub.excerpt || sub.content || data.content || '').slice(0, 600),
                  });
                }
              } else {
                contextDocs.push({
                  title: docTitle,
                  url: data.url || '#',
                  content: (data.content || data.excerpt || '').slice(0, 800),
                });
              }
            }
          }
        }
      }
    } catch (e) {
      console.warn('Pagefind context search notice:', e);
    }

    try {
      const res = await fetch('/api/ai-search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: q, contextDocs, locale }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'DeepSeek API 响应异常');
      }

      setAnswer(data.answer || '未能生成有效答复');
      if (Array.isArray(data.sources) && data.sources.length > 0) {
        setSources(data.sources);
      } else {
        setSources(contextDocs);
      }
    } catch (err: any) {
      setError(err.message || 'AI 请求失败，请稍后重试。');
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <div className="ai-search-backdrop" onClick={onClose} />
      <div className="ai-search-modal" role="dialog" aria-modal="true">
        <div className="ai-search-header">
          <div className="ai-search-title">
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2">
              <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
            </svg>
            <span>{t.modalTitle}</span>
            <span className="ai-search-badge">{t.badge}</span>
          </div>
          <button className="ai-search-close-btn" onClick={onClose} aria-label="关闭">
            ✕
          </button>
        </div>

        <div className="ai-search-body">
          <div className="ai-search-input-wrapper">
            <input
              ref={inputRef}
              type="text"
              className="ai-search-input"
              placeholder={t.placeholder}
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
            />
            <button
              className="ai-search-submit-btn"
              onClick={() => handleSearch()}
              disabled={loading || !query.trim()}
            >
              {loading ? t.thinkingBtn : t.submitBtn}
            </button>
          </div>

          {loading && (
            <div className="ai-search-loading">
              <div className="ai-spinner" />
              <span>{t.loadingText}</span>
            </div>
          )}

          {error && (
            <div className="ai-search-result-card" style={{ borderColor: '#ef4444', color: '#ef4444' }}>
              <strong>{t.errorPrefix}</strong> {error}
            </div>
          )}

          {answer && (
            <div className="ai-search-result-card">
              <div className="ai-search-answer">
                <MarkdownRenderer content={answer} />
              </div>

              {sources.length > 0 && (
                <div className="ai-search-sources">
                  <div className="ai-search-sources-title">{t.sourcesTitle}</div>
                  <ol style={{ margin: '0.35rem 0 0 0', paddingLeft: '1.25rem', lineHeight: '1.65' }}>
                    {sources.map((s, i) => (
                      <li key={i} style={{ marginBottom: '0.3rem' }}>
                        <a href={s.url} target="_blank" rel="noreferrer" className="ai-source-link">
                          {s.title}
                        </a>
                      </li>
                    ))}
                  </ol>
                </div>
              )}

              <div className="ai-action-bar">
                <span className="ai-notice">{t.aiNotice}</span>
                <div className="ai-action-buttons">
                  <button
                    className={`ai-action-btn ${liked ? 'active' : ''}`}
                    onClick={() => { setLiked(!liked); setDisliked(false); }}
                    title="点赞"
                  >
                    👍 {liked ? t.liked : ''}
                  </button>
                  <button
                    className={`ai-action-btn ${disliked ? 'active' : ''}`}
                    onClick={() => { setDisliked(!disliked); setLiked(false); }}
                    title="踩"
                  >
                    👎
                  </button>
                  <button className="ai-action-btn" onClick={handleCopy} title="复制回答">
                    📋 {copied ? t.copied : t.copy}
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
